from typing import Literal, TypedDict

from pydantic import BaseModel, ConfigDict, Field


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class File(StrictModel):
    path: str = Field(
        description="The path of the file to be created"
    )

    purpose: str = Field(
        description="The purpose of the file"
    )


class Plan(StrictModel):
    name: str = Field(
        description="The name of the app to be built"
    )

    description: str = Field(
        description="A one-line description of the app"
    )

    techstack: str = Field(
        description="The technology stack used for the app"
    )

    features: list[str] = Field(
        description="The features the app should have"
    )

    files: list[File] = Field(
        description="The files that should be created"
    )


class ImplementationTask(StrictModel):
    filepath: str = Field(
        description="The path of the file to implement"
    )

    task_description: str = Field(
        description="The implementation instructions for the file"
    )


class TaskPlan(StrictModel):
    implementation_steps: list[ImplementationTask] = Field(
        description="The ordered implementation tasks"
    )


class CoderState(BaseModel):
    task_plan: TaskPlan = Field(
        description="The task plan generated by the architect"
    )

    current_step_idx: int = Field(
        default=0,
        description="The current implementation step index"
    )

    current_file_content: str | None = Field(
        default=None,
        description="The current file content, if any"
    )


class AgentState(TypedDict, total=False):
    user_prompt: str
    browser_preview: bool
    plan: Plan
    task_plan: TaskPlan
    coder_state: CoderState
    status: Literal["CODING", "DONE"]
